name: Build kerf1

on:
  workflow_dispatch:
  push:
    branches:
      - gh-action

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Download libedit (3.1 thrysoee.dk macports) w/ checksum
        run: |
          wget https://thrysoee.dk/editline/libedit-20210910-3.1.tar.gz
          echo "b7361c277f971ebe87e0e539e5e1fb01a4ca1bbab61e199eb97774d8b60dddeb9e35796faf9cc68eb86d1890e8aac11db13b44b57ccc8302d559741fbe9d979e  libedit-20210910-3.1.tar.gz" | sha512sum -c

      - name: Install libedit
        run: |
          tar -xf libedit-20210910-3.1.tar.gz
          cd libedit-20210910-3.1
          ./configure
          make
          sudo make install

      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Build kerf
        run: |
          cd ${{GITHUB_WORKSPACE}}/src/
          make release

      - name: Upload build
        uses: actions/upload-artifact@v3
        with:
          name: kerf-linux
          path: ${{GITHUB_WORKSPACE}}/src/kerf
          if-no-files-found: error
          retention-days: 1
