name: Build kerf1

on:
  workflow_dispatch:
  push:
    branches:
      - testing2

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Build kerf
        run: |
          cd $GITHUB_WORKSPACE/src/
          make all
          mv kerf kerf-macos

      - name: Upload build
        uses: actions/upload-artifact@v3
        with:
          name: kerf-macOS
          path: ${{ github.workspace }}/src/kerf-macos
          if-no-files-found: error

  release:
    runs-on: ubuntu-latest
    needs: [build-macos]
    steps:
      - name: Download macOS artifact
        uses: actions/download-artifact@v3
        with:
          name: kerf-macOS
          path: output

      - name: Make binaries executable
        run: |
          chmod +x output/kerf-macOS

      - name: Draft Release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          tag_name: ${{ steps.vars.outputs.tag_name }}
          files: |
            output/kerf-macOS 
